Repository PennLINC/qsiprep, pull requests merged in 2024-12, with the labels that each got.

#892 Calculate patch radius from number of volumes in DWI run
  qsiprep/cli/parser.py
  qsiprep/data/boilerplate.bib
  qsiprep/workflows/dwi/hmc.py
  qsiprep/workflows/dwi/merge.py
  qsiprep/workflows/fieldmap/syn.py
Labels: bug, breaking-change

#896 Link to NiPreps contributing guidelines
  CONTRIBUTING.md
Labels: documentation

#901 Fix session processing for datasets with mixed modalities
  qsiprep/cli/parser.py
  qsiprep/utils/bids.py
Labels: bug

#902 Use DIPY version of patch2self
  .circleci/config.yml
  pyproject.toml
  qsiprep/interfaces/denoise.py
  qsiprep/interfaces/dipy.py
  qsiprep/interfaces/patch2self.py
  qsiprep/tests/conftest.py
  qsiprep/tests/data/forrest_gump_patch2self_outputs.txt
  qsiprep/tests/test_cli.py
  qsiprep/tests/test_interfaces_dipy.py
  qsiprep/tests/test_interfaces_mrtrix3.py
Labels: bug
